export const HAPPENINGS = [
  'Acontecimento 1',
  'Acontecimento 2',
  'Acontecimento 3',
  'Acontecimento 4',
  'Acontecimento 5',
  'Acontecimento 6',
  'Acontecimento 7',
  'Acontecimento 8',
  'Acontecimento 9',
  'Acontecimento 10',
  'Acontecimento 11',
  'Acontecimento 12',
  'Acontecimento 13',
  'Acontecimento 14',
  'Acontecimento 15',
  'Acontecimento 16',
  'Acontecimento 17',
  'Acontecimento 18',
  'Acontecimento 19',
  'Acontecimento 20',
  'Acontecimento 21',
  'Acontecimento 22',
  'Acontecimento 23',
  'Acontecimento 24',
  'Acontecimento 25',
]